config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'up' => 'rails/health#show', as: :rails_health_check

  scope module: :web do
    root 'home#index'

    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete 'auth/logout', to: 'auth#logout'

    resources :repositories, only: %i[index show new create] do
      scope module: :repositories do
        resources :checks, only: %i[create show]
      end
    end
  end

  namespace :api do
    resources :checks, only: %i[create]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/repository.rb
# frozen_string_literal: true

class Repository < ApplicationRecord
  extend Enumerize

  belongs_to :user
  has_many :checks, dependent: :destroy

  validates :github_id, uniqueness: true, presence: true

  enumerize :language, in: %w[ruby javascript]
end

app/models/repository/check.rb
# frozen_string_literal: true

class Repository::Check < ApplicationRecord
  include AASM

  belongs_to :repository

  aasm do
    state :created, initial: true
    state :check_running, :finished, :failed

    event :run_check do
      transitions from: :created, to: :check_running
    end

    event :mark_as_finished do
      transitions from: :check_running, to: :finished
    end

    event :mark_as_failed do
      transitions from: :check_running, to: :failed
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :repositories, dependent: :destroy

  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { minimum: 2, maximum: 50 },
                    format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/api/application_controller.rb
# frozen_string_literal: true

module Api
  class ApplicationController < ApplicationController
  end
end

app/controllers/api/checks_controller.rb
# frozen_string_literal: true

module Api
  class ChecksController < Api::ApplicationController
    skip_before_action :verify_authenticity_token

    def create
      repository = Repository.find_by(github_id: params['repository']['id'])

      unless repository
        head :not_found
        return
      end

      check = repository.checks.create

      RepositoryCheckJob.perform_later(check.id)

      head :ok
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :signed_in?, :current_user

  include AuthManagement
  include Pundit::Authorization
end

app/controllers/concerns/auth_management.rb
# frozen_string_literal: true

module AuthManagement
  def sign_in(user)
    session[:user_id] = user.id
  end

  def sign_out
    session.delete(:user_id)
    session.clear
  end

  def signed_in?
    session[:user_id].present? && current_user.present?
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def authenticate_user!
    return if signed_in?

    redirect_to root_path, alert: t('flash.auth.shoud_sign_in')
  end
end

app/controllers/web/application_controller.rb
# frozen_string_literal: true

module Web
  class ApplicationController < ApplicationController
  end
end

app/controllers/web/auth_controller.rb
# frozen_string_literal: true

module Web
  class AuthController < Web::ApplicationController
    def callback
      user_data = request.env['omniauth.auth']
      user = find_or_initialize_user(user_data)

      if user.save
        sign_in(user)
        flash[:notice] = t('flash.auth.sign_in.success')
      else
        flash[:alert] = t('flash.auth.sign_in.error')
      end

      redirect_to root_path
    end

    def logout
      sign_out
      redirect_to root_path, notice: t('flash.auth.sign_out.success')
    end

    private

    def find_or_initialize_user(user_data)
      email = user_data.dig(:info, :email).downcase
      user = User.find_or_initialize_by(email:)
      assign_user_attributes(user, user_data)
    end

    def assign_user_attributes(user, user_data)
      nickname = user_data.dig(:info, :nickname)
      token = user_data.dig(:credentials, :token)
      provider = user_data[:provider]
      uid = user_data[:uid]

      attributes = { nickname:, token:, provider:, uid: }

      user.assign_attributes(attributes)
      user
    end
  end
end

app/controllers/web/home_controller.rb
# frozen_string_literal: true

module Web
  class HomeController < Web::ApplicationController
    def index; end
  end
end

app/controllers/web/repositories/application_controller.rb
# frozen_string_literal: true

module Web
  module Repositories
    class ApplicationController < Web::ApplicationController
    end
  end
end

app/controllers/web/repositories/checks_controller.rb
# frozen_string_literal: true

module Web
  module Repositories
    class ChecksController < Web::Repositories::ApplicationController
      def show
        @check = Repository::Check.includes(:repository).find(params[:id])
        authorize @check
      end

      def create
        @repository = Repository.find(params[:repository_id])

        check = @repository.checks.create
        authorize check

        RepositoryCheckJob.perform_later(check.id)

        flash[:notice] = t('flash.repositories.checks.create.success')
        redirect_to @repository
      end
    end
  end
end

app/controllers/web/repositories_controller.rb
# frozen_string_literal: true

module Web
  class RepositoriesController < Web::ApplicationController
    before_action :authenticate_user!

    def index
      @repositories = current_user.repositories.includes(:checks)
    end

    def show
      @repository = Repository.find(params[:id])
      authorize @repository

      @checks = @repository.checks.order(created_at: :desc)
    end

    def new
      @repository = current_user.repositories.build
      authorize @repository

      @github_client = ApplicationContainer[:github_client].new(@repository, current_user)

      @repositories = @github_client.filtered_by_languages_repos.map { |repo| [repo[:full_name], repo[:id]] }
    end

    def create
      @repository = current_user.repositories.find_or_initialize_by(repository_params)
      authorize @repository

      if @repository.save
        RepositoryLoadInfoJob.perform_later(@repository.id)

        flash[:notice] = t('flash.repositories.create.success')
        redirect_to repositories_path
      else
        render :new, status: :unprocessable_entity
      end
    end

    private

    def repository_params
      params.require(:repository).permit(:github_id)
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def github_file_link(check, filename)
    repository = check.repository

    link_to(filename, "https://github.com/#{repository.full_name}/blob/#{check.commit_id}/#{filename}")
  end

  def github_commit_link(check)
    return '' unless check.commit_id

    short_commt = check.commit_id[0..5]
    repository = check.repository

    link_to(short_commt, "https://github.com/#{repository.full_name}/commit/#{short_commt}")
  end
end

app/views/home/index.html.slim
| Home View

app/views/layouts/application.html.slim
doctype html
html.h-100
  head
    title Rails Project 66
    meta name='viewport' content='width=device-width,initial-scale=1'
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module'

  body.d-flex.flex-column.h-100
    = render 'layouts/shared/navbar'
    = render 'layouts/shared/flash'
    main
      .mt-4.mb-5.pb-5
        .container
          .p-4.align-items-center.border.shadow.bg-white.rounded-3
            .mb-4
              h1
            = yield

    = render 'layouts/shared/footer'

app/views/layouts/shared/_flash.html.slim
- if flash[:notice]
  .container.my-2
    p.alert.alert-info role='alert'
      = notice

- if flash[:alert]
  .container.my-2
    p.alert.alert-danger role='alert'
      = alert

app/views/layouts/shared/_footer.html.slim
footer.bg-dark.text-light.mt-auto
  .container-xl
    .row.py-2 © Hexlet Ltd, 2024

app/views/layouts/shared/_navbar.html.slim
.container.mb-2
  .d-flex.flex-wrap.align-items-center.py-2.border-bottom
    .navbar.navbar-expand-md.navbar-light.me-auto
      = link_to root_path, class: 'navbar-brand me-md-4'
        = image_tag('https://upload.wikimedia.org/wikipedia/commons/2/25/Hexlet-logo.jpg', height: '30', width: '30')
      #navbarToggler.collapse.navbar-collapse
        ul.nav.nav-pills.flex-grow-1.navbar-nav.me-auto
          li.nav-item.me-2
            = link_to t('.main_page'), root_path, class: 'nav-link text-dark'
          - if signed_in?
            li.nav-item.me-2
              = link_to t('.repositories'), repositories_path, class: 'text-dark nav-link'

    ul.nav.nav-pills
      - if signed_in?
        li.nav-item
          = link_to current_user.email, '#', class: 'nav-link text-secondary'
        li.nav-item.me-2
          = button_to t('.sign_out'), auth_logout_path, method: :delete, class: 'nav-link text-dark'
      - else
        li.nav-item.me-2
          = button_to auth_request_path(:github), data: { turbo: false }, class: 'nav-link text-dark' do
            span class='bi bi-github me-2'
            span = t('.sign_in')

app/views/web/home/index.html.slim
.mb-4
  h1
.display-4.fw-bold.mb-0
  = t('.hexlet_greetings')
p.mb-4
  = t('.hexlet_greetings_description')
h2.fw-bold
  = t('.project_name')
p
  = t('.project_description')

= link_to t('.learn_more'),
          'https://ru.hexlet.io/programs/rails/projects/66',
          class: 'btn btn-primary btn-lg px-4 mt-3 fw-bold'

app/views/web/repositories/_form.html.slim
= simple_form_for @repository, url: repositories_path, method: :post do |f|
  = f.input :github_id, as: :select, collection: @repositories
  = f.button :submit, class: 'btn btn btn-success'

app/views/web/repositories/checks/show.html.slim
= link_to t('.back_to_repository'), @check.repository, class: 'btn btn-primary mb-4'

h1 = t('.title', check_id: @check.id)

table.table
  tbody
    tr
      td = t('.created_at')
      td = l(@check.created_at)
    tr
      td = t('.status')
      td = @check.aasm.human_state
    tr
      td = t('.check_passed?')
      td = @check.passed?
    tr
      td = t('.comments_count')
      td = @check.linter_check_result['offenses_count']
    tr
      td = t('.commit_id')
      td = github_commit_link(@check)

table.table.table-hover.mb-5
  thead
    tr
      th = t('.message')
      th = t('.rule_id')
      th = t('.line_and_column')
  tbody
    - if @check.linter_check_result['offenses_count']&.positive?
      - @check.linter_check_result['files'].each do |filename, offenses|
        tr
          td (colspan = "4")
            = github_file_link(@check, filename)
        - offenses.each do |offense|
          tr
            td = offense['message']
            td = offense['cop_name']
            td = "#{offense['start_line']}:#{offense['start_column']}"

app/views/web/repositories/index.html.slim
= link_to t('.add_new'), new_repository_path, class: 'btn btn-primary'

table.table.table-striped.table-hover.mt-4
  thead
    tr
      th scope='col' = t('.name')
      th scope='col' = t('.language')
      th scope='col' = t('.last_check_status')

  tbody
    - @repositories.each do |repository|
      tr
        td
          = link_to repository.name || '-', repository_path(repository)
        td
          = repository.language || ''
        td
          - if repository.checks.any?
            = repository.checks.last.passed?
          - else
            = t('.not_checked_yet')

app/views/web/repositories/new.html.slim
= render 'form', repository: @repository

app/views/web/repositories/show.html.slim
h1
  = @repository.full_name

= button_to t('.check'), repository_checks_path(@repository), class: 'btn btn-primary mb-4'

p
  strong.me-2 = t('.full_name')
  = @repository.full_name
p
  strong.me-2 = t('.language')
  = @repository.language
p
  strong.me-2 = t('.created_at')
  = l(@repository.created_at)
p
  strong.me-2 = t('.updated_at')
  = l(@repository.updated_at)

hr

- if @checks
  table.table.table-striped
    thead
      tr
        th scope='col'
        th scope='col' = t('.status')
        th scope='col' = t('.commit_id')
        th scope='col' = t('.check_passed?')
        th scope='col' = t('.created_at')
    tbody
      - @checks.each do |check|
        tr
          td = link_to(check.id, repository_check_path(@repository, check))
          td = check.aasm.human_state
          td = github_commit_link(check)
          td = check.passed?
          td = l(check.created_at)